---

- name: find ONOS_CLI_POD
  command:
    argv:
      - kubectl
      - -n
      - aether-roc
      - get
      - pods
      - -l
      - name=onos-cli
      - -o
      - name
  register: result
  when: inventory_hostname in groups['master_nodes']

- set_fact:
    ONOS_CLI_POD: "{{ result.stdout }}"
  when: inventory_hostname in groups['master_nodes']

- name: find API_SERVICE
  command:
    argv:
      - kubectl
      - -n
      - aether-roc
      - get
      - services
      - -l
      - app.kubernetes.io/name=aether-roc-api
      - -o
      - jsonpath={.items[0].metadata.name}
  register: result
  when: inventory_hostname in groups['master_nodes']

- set_fact:
    API_SERVICE: "{{ result.stdout }}"
  when: inventory_hostname in groups['master_nodes']

- debug:
    var: "ONOS_CLI_POD"
  when: inventory_hostname in groups['master_nodes']

- debug:
    var: "API_SERVICE"
  when: inventory_hostname in groups['master_nodes']

- name: remove /tmp/roc-models.yaml
  file:
    path: /tmp/roc-models.json
    state: absent
  when: inventory_hostname in groups['master_nodes']

- name: Copy models file to /tmp/roc-models.json
  template:
    src: "{{ ROOT_DIR }}/{{ amp.roc_models }}"
    dest: "/tmp/roc-models.json"
  when: inventory_hostname in groups['master_nodes']

- name: read rendered ROC models payload
  slurp:
    src: /tmp/roc-models.json
  register: roc_models_payload
  when: inventory_hostname in groups['master_nodes']

#TODO use ansible kubectl module
- name: load roc models file
  command:
    argv:
      - kubectl
      - -n
      - aether-roc
      - exec
      - -i
      - "{{ ONOS_CLI_POD }}"
      - --
      - curl
      - -s
      - -f
      - -L
      - -X
      - PATCH
      - "http://{{ API_SERVICE }}:8181/aether-roc-api"
      - --header
      - Content-Type: application/json
      - --data-binary
      - '@-'
  args:
    stdin: "{{ roc_models_payload.content | b64decode }}"
  register: result
  until: result.stdout.find("command terminated") == -1
  retries: 5
  delay: 10
  when: inventory_hostname in groups['master_nodes']

- debug:
    var: result.stdout
  when: inventory_hostname in groups['master_nodes']
