[all]
# Optional for password-based access:
# node1 ansible_host=127.0.0.1 ansible_user=<username> ansible_password=<password> ansible_sudo_pass=<sudo-password>
node1 ansible_host=127.0.0.1 ansible_user=aether
#node2 ansible_host=10.76.28.115 ansible_user=aether
#node3 ansible_host=10.76.28.117 ansible_user=aether
#node4 ansible_host=10.76.28.119 ansible_user=aether

[master_nodes]
node1

[worker_nodes]
#node2
#node3

[gnbsim_nodes]
node1
#node2
#node4

[oai_nodes]
#node2
#node4

[ueransim_nodes]
#node2
#node4

[srsran_nodes]
#node2
#node4

[ocudu_nodes]
#node2
#node4

[oscric_nodes]
#node2
#node4

[n3iwf_nodes]
#node2
#node4
