{% set local_hosts = [None, '', 'localhost', '127.0.0.1', '::1'] %}
{% set node_host = ansible_host | default('', true) %}
token: {{ k8s.rke2.config.token }}
node-name: {{ inventory_hostname }}
node-ip: {{ ((((ansible_default_ipv4 | default({}))['address']) | mandatory('ansible_default_ipv4.address is required to set node-ip when ansible_host is empty/localhost')) if node_host in local_hosts else node_host) | quote }}
cni: multus,canal
cluster-cidr: 10.42.0.0/16
service-cidr: 10.43.0.0/16
kubelet-arg:
- --allowed-unsafe-sysctls=net.*
kube-proxy-arg:
- --metrics-bind-address=0.0.0.0:10249
kube-apiserver-arg:
- --service-node-port-range=2000-36767
node-label:
- "node-role.aetherproject.org/5gc=true"
- "node-role.aetherproject.org/upf=true"
