amp:
  data_iface: enp193s0f0

  monitor:
    helm:
      chart_ref: rancher/rancher-monitoring
      chart_version: 110.0.1+up80.9.1-rancher.19

  monitor_crd:
    helm:
      chart_ref: rancher/rancher-monitoring-crd
      chart_version: 110.0.1+up80.9.1-rancher.19

