amp:
  data_iface: enp193s0f0

  monitor:
    helm:
      chart_ref: rancher/rancher-monitoring
      chart_version: 108.0.4+up77.9.1-rancher.14

  monitor_crd:
    helm:
      chart_ref: rancher/rancher-monitoring-crd
      chart_version: 108.0.4+up77.9.1-rancher.14

