---

- name: find {{ core.data_iface }}'s subnet for RAN
  command:
    argv:
      - ip
      - -o
      - route
      - show
      - dev
      - "{{ core.data_iface }}"
  register: result
  changed_when: false
  failed_when: false
  when: inventory_hostname in groups['master_nodes']
  become: true

# TODO: check if interface subnet is valid
- set_fact:
    ran_subnet: >-
      {{
        (
          result.stdout_lines
          | default([])
          | select('search', ' proto kernel ')
          | map('regex_replace', '^([^ ]+).*$','\\1')
          | list
          | first
          | default('')
        ) if (core.ran_subnet == '') else core.ran_subnet
      }}
  when: inventory_hostname in groups['master_nodes']

- debug:
    var: "ran_subnet"

- name: remove /tmp/sdcore-4g-values.yaml
  file:
    path: "/tmp/sdcore-4g-values.yaml"
    state: absent
  when: inventory_hostname in groups['master_nodes']

- name: copy {{ ROOT_DIR }}/{{ core.values_file }} to /tmp/sdcore-4g-values.yaml
  template:
    src: "{{ ROOT_DIR }}/{{ core.values_file }}"
    dest: "/tmp/sdcore-4g-values.yaml"
  when: inventory_hostname in groups['master_nodes']

- set_fact:
    core_helm_requires_repo_update: "{{ not (core.helm.chart_ref is match('^oci://')) }}"
  when: inventory_hostname in groups['master_nodes']

# - name: update aether 5gc helm dependencies
#   shell: |
#     helm dep up "{{ core.helm.chart_ref }}"
#   when: inventory_hostname in groups['master_nodes']

# TODO: add systems check to avoid issues (e.g., mongodb needing avx support)
- name: deploy aether 4gc
  block:
    - name: deploy aether 4gc
      kubernetes.core.helm:
        update_repo_cache: "{{ core_helm_requires_repo_update }}"
        name: sd-core
        release_namespace: omec
        create_namespace: true
        chart_ref: "{{ core.helm.chart_ref }}"
        chart_version: "{{ core.helm.chart_version }}"
        values_files:
          - /tmp/sdcore-4g-values.yaml
        wait: true
        wait_timeout: "1m30s"
        force: true
      when: inventory_hostname in groups['master_nodes']

  rescue:
    - name: Get Pods Status
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: omec
      register: pod_status
      changed_when: false
      when: inventory_hostname in groups['master_nodes']

    - name: restart Pods if not running
      kubernetes.core.k8s:
        api_version: v1
        kind: Pod
        namespace: omec
        name: "{{ item.metadata.name }}"
        state: absent
      loop: "{{ pod_status.resources | default([]) }}"
      loop_control:
        label: "{{ item.metadata.name }}"
      register: pod_restart
      when:
        - inventory_hostname in groups['master_nodes']
        - (item.status.phase | default('')) != 'Running'
      ignore_errors: yes
  always:
    - pause:
        seconds: 180
