# SRS E2E O-RAN testbed example PTP configuration. It is based on the
# Telecom G.8275.1 example configuration provided with ptp4l, with some
# modifications to make the LLS-C1 setup work with a wide range of RUs.
[global]
domainNumber                    24
dataset_comparison              G.8275.x
G.8275.defaultDS.localPriority  128
logAnnounceInterval             1
logSyncInterval                 -4
logMinDelayReqInterval          -4
serverOnly                      1
G.8275.portDS.localPriority     128
maxStepsRemoved                 255

#
# Transport options.
#
uds_address                     /var/run/ptp4l
network_transport               L2
delay_mechanism                 E2E
time_stamping                   hardware
tsproc_mode                     filter
delay_filter                    moving_median
delay_filter_length             10
egressLatency                   0
ingressLatency                  0

#
# Clock description.
#
clockClass                      6
# clock_type                      OC
# clockAccuracy                   0x20
