---

- name: delete local charts from /tmp/sdcore-helm-charts/
  file:
    path: /tmp/sdcore-helm-charts/
    state: absent
  when: inventory_hostname in groups['master_nodes']  and core.helm.local_charts
  ignore_errors: yes

- name: remove aether 5gc
  kubernetes.core.helm:
    name: sd-core
    release_namespace: aether-5gc
    state: absent
    wait: true
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: waiting for aether pods to terminate
  command:
    argv:
      - kubectl
      - wait
      - -n
      - aether-5gc
      - --for=delete
      - --all=true
      - -l
      - app!=ue
      - pod
      - --timeout=180s
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

- name: delete namespace aether-5gc
  command:
    argv:
      - kubectl
      - delete
      - namespace
      - aether-5gc
  when: inventory_hostname in groups['master_nodes']
  ignore_errors: yes

