---

# TODO: running on master node for now (fix to run on multiple nodes)

- name: check VF resources
  block:
    - name: Get number of VFs available for interface {{ core.data_iface }}
      shell: ip link show "{{ core.data_iface }}" | grep -c vf
      register: vf_status
      changed_when: false

    - debug:
         var=vf_status.stdout

    - name: verify the required VF resources available in {{ core.data_iface }}
      ansible.builtin.assert:
        that:
          - vf_status.stdout | int >= 2

  when: inventory_hostname in groups['master_nodes'] and core.upf.mode == "dpdk"
