# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Override values for omec-user-plane Helm Chart
# https://github.com/omec-project/sdcore-helm-charts/blob/main/bess-upf/values.yaml
enable: true
resources:
  enabled: false
# images:
#   repository: ""
#   tags:
#     bess: <bess image tag>
#     pfcpiface: <pfcp image tag>
#     tools: <aether-pod-init image tag>
config:
  upf:
    name: "aether-upf"
    sriov:
      enabled: {{ (core.upf.mode == 'dpdk') | ternary('true', 'false') }}
    hugepage:
      enabled: {{ (core.upf.mode == 'dpdk') | ternary('true', 'false') }}
    routes:
      - to: {{ ansible_default_ipv4.address }}
        via: 169.254.1.1
    enb:
      subnet: {{ ran_subnet }} # Subnet for the gNB network
    access:
      ipam: static
      cniPlugin: {{ 'vfioveth' if core.upf.mode == 'dpdk' else 'macvlan' }}
{% if core.upf.mode == 'dpdk' %}
      resourceName: "intel.com/intel_sriov_vfio_access"
{% endif %}
      iface: {{ core.data_iface }}
      gateway: {{ access_gw }}
      ip: {{ upf_access_ip }}
    core:
      ipam: static
      cniPlugin: {{ 'vfioveth' if core.upf.mode == 'dpdk' else 'macvlan' }}
{% if core.upf.mode == 'dpdk' %}
      resourceName: "intel.com/intel_sriov_vfio_core"
{% endif %}
      iface: {{ core.data_iface }}
      gateway: {{ core_gw }}
      ip: {{ upf_core_ip }}
    closedLoop: {{ core.closed_loop | default('false') | lower }}
    cfgFiles:
      upf.jsonc:
        mode: {{ core.upf.mode }}
        hwcksum: true
        log_level: "info"
        measure_upf: true
        measure_flow: true
        gtppsc: true        # Extension header enabled in 5G.
        # DDP is INTEL NIC's specific feature (supported in E810 series)
        # which helps to improve UPF packet processing performance.
        # For more details on DDP feature and its usage please refer
        # "https://www.intel.com/content/www/us/en/download/19660/intel-ethernet-800-series-dynamic-device-personalization-ddp-for-telecommunication-comms-package.html"
        ddp: false          # this parameter is only used/relevant when deploying the UPF in 'dpdk' mode
        cpiface:
          dnn: "internet"              # Must match Slice dnn
          hostname: "upf"
          #http_port: "8080"
          enable_ue_ip_alloc: true    # If true, UPF allocates address from following pool
          ue_ip_pool: {{ upf_ue_ip_pool }} # IP pool used UEs if enable_ue_ip_alloc=true
        slice_rate_limit_config:       # Slice-level rate limiting (also controlled by ROC)
          # Uplink
          n6_bps: 10000000000          # 10Gbps
          n6_burst_bytes: 12500000     # 10ms * 10Gbps
          # Downlink
          n3_bps: 10000000000          # 10Gbps
          n3_burst_bytes: 12500000     # 10ms * 10Gbps
