
gnbsim:
  docker:
    container:
      image: ghcr.io/omec-project/5gc-gnbsim:rel-1.9.0
      prefix: gnbsim
      count: 2
    network:
      macvlan:
        name: gnbnet

  router:
    mcavlan:
      subnet_prefix: "172.20"
