{
 "title": "enodebd dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "enodeb",
    "label": "enodeb",
    "query": {
     "query": "label_values(enodeb_current_status, serial_number)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$enodeb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "enodeb" },
  {
   "title": "eNodeB Serial Number",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "enodeb",
   "options": { "content": "<center><h1>${enodeb}</h1>" }
  },
  {
   "title": "Last Configured",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "repeat": "enodeb",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "enodeb_current_status{serial_number=\"$enodeb\"}",
     "legendFormat": "eNodeB Status"
    },
    {
     "expr": "enodeb_last_configured_time{serial_number=\"$enodeb\"}*1000",
     "legendFormat": "Last Configured at"
    }
   ]
  },
  {
   "title": "RF Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "repeat": "enodeb",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "enodeb_op_status{serial_number=\"$enodeb\"}"
    }
   ]
  },
  {
   "title": "GPS Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "repeat": "enodeb",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "enodeb_gps_status{serial_number=\"$enodeb\"}"
    }
   ]
  },
  {
   "title": "Coordinate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "repeat": "enodeb",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "enodeb_gps_status_lat{serial_number=\"$enodeb\"}",
     "legendFormat": "Latitude"
    },
    {
     "expr": "enodeb_gps_status_long{serial_number=\"$enodeb\"}",
     "legendFormat": "Longtitude"
    }
   ]
  }
 ]
}