---
- name: pull {{ ueransim.docker.container.image }} image
  community.docker.docker_image:
    name: "{{ ueransim.docker.container.image }}"
    source: pull
  when: inventory_hostname in groups['ueransim_nodes']
  become: true

- set_fact:
    subnet: "{{ core.upf.access_subnet | regex_replace('[0-9]+/24', '0/24') }}"
  when: inventory_hostname in groups['ueransim_nodes']

- name: configure static route for upf traffic on ueransim node
  command:
    argv:
      - ip
      - route
      - add
      - "{{ subnet }}"
      - via
      - "{{ core.amf.ip }}"
  become: true
  when: (inventory_hostname in groups['ueransim_nodes']) and (inventory_hostname not in groups['master_nodes']) and core.upf.multihop_gnb == false
