---
- name: delete {{ ueransim.docker.container.name }} container
  community.docker.docker_container:
    name: "{{ ueransim.docker.container.name }}"
    state: absent
  when: inventory_hostname in groups['ueransim_nodes']
  become: true
