# SPDX-FileCopyrightText: 2026 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0

name: Aether OnRamp Link Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check documentation links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          jobSummary: true
          args: >-
            --verbose
            --no-progress
            --accept 200,429
            --exclude 'http://<server_ip>:31194'
            --exclude 'http://<server_ip>:30950'
            './README.md'
            './vars/**/*.md'
            './.github/**/*.md'
